### PR TITLE
Ensure CopyElement does not break UTF-8 characters

### LINKED ISSUE #188: UTF-8 characters can be broken in two in CopyElement, resulting in invalid records
`TL;DR`: The custom, optimized code in `CopyElement.java` that cleans up the headers of xml exports relies on `xmlInputStream.readNBytes(1024);`. If that 1024 bytes offset happens to split a multi-byte UTF-8 character in two, it results in illegal UTF and invalid and unparseable OAI xml. 

(much) Longer version: 

This happens somewhat rarely (at least on an instance where most of the metadata text is encoded using Latin characters), which is the reason we have only discovered it now. It is nevertheless a serious problem. As of yesterday, a non-Dataverse harvester that relies on ListRecords could not harvest the full holdings from IQSS - it was reliably bombing on the 270th results page that contained a record subject to this bug. 

For the record, I'm kicking myself now, I don't know how I didn't think of this when we were working on the new XOAI.

An exhibit A: 

We have a dataset with a mostly standard-ASCII text in the description, except for the fancy apostrophe in the word "farmer’s" (see below). Which is a UTF-8 character made of 3 bytes: `<E2><80><99>`. The oai_dc metadata for it is properly exported and cached, so calling `/api/datasets/export?exporter=oai_dc` produces a perfectly valid XML record: 

```
<oai_dc:dc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd"><dc:title>Impact of micronutrients on upland rice yield, Nicaragua</dc:title><dc:identifier>https://doi.org/10.7910/DVN/IBDWAV</dc:identifier><dc:creator>Siles, Pablo</dc:creator><dc:creator>Tellez, Orlando</dc:creator><dc:creator>Peng, Yuan-Ching</dc:creator><dc:creator>Zeledón, Yasser</dc:creator><dc:publisher>Harvard Dataverse</dc:publisher><dc:description>This dataset contains information of experiments carried out upland rice in two regions of Nicaragua (Caribbean and Pacific Region), as well as a compilation of soils data from different regions in Nicaragua collected from 2015 to 2019. The experiments were designed to explore the effects of micronutrients in the yield of upland rice. The experiments were carried out on farmer’s field during the 2018 production cycle, the dataset contains yield and aerial biomass of the experiments.</dc:description><dc:subject>Agricultural Sciences</dc:subject><dc:subject>Earth and Environmental Sciences</dc:subject><dc:subject>Upland rice</dc:subject><dc:subject>Micronutrients</dc:subject><dc:subject>Crop yield</dc:subject><dc:subject>Zinc</dc:subject><dc:subject>Boron</dc:subject><dc:subject>Latin America and the Caribbean</dc:subject><dc:subject>Multifunctional Landscapes</dc:subject><dc:language>Spanish, Castilian</dc:language><dc:date>2019-02</dc:date><dc:contributor>Garcia, Carolina</dc:contributor><dc:type>Experimental Data</dc:type><dc:type>Environmental Data</dc:type></oai_dc:dc>
```

However, 

Exhibit B:

If you ask for the OAI record for this dataset, you get a response that's not valid XML, because it contains some bytes that are not valid UTF-8: 

```
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd"><responseDate>2023-09-14T17:23:45Z</responseDate><request verb="GetRecord" identifier="doi:10.7910/DVN/IBDWAV" metadataPrefix="oai_dc">https://dataverse.harvard.edu/oai</request><GetRecord><record><header><identifier>doi:10.7910/DVN/IBDWAV</identifier><datestamp>2023-03-10T07:14:37Z</datestamp><setSpec>IQSS</setSpec><setSpec>AllianceBioversityCIAT</setSpec></header><metadata><oai_dc:dc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd"><dc:title>Impact of micronutrients on upland rice yield, Nicaragua</dc:title><dc:identifier>https://doi.org/10.7910/DVN/IBDWAV</dc:identifier><dc:creator>Siles, Pablo</dc:creator><dc:creator>Tellez, Orlando</dc:creator><dc:creator>Peng, Yuan-Ching</dc:creator><dc:creator>Zeledón, Yasser</dc:creator><dc:publisher>Harvard Dataverse</dc:publisher><dc:description>This dataset contains information of experiments carried out upland rice in two regions of Nicaragua (Caribbean and Pacific Region), as well as a compilation of soils data from different regions in Nicaragua collected from 2015 to 2019. The experiments were designed to explore the effects of micronutrients in the yield of upland rice. The experiments were carried out on farmer�?s field during the 2018 production cycle, the dataset contains yield and aerial biomass of the experiments.</dc:description><dc:subject>Agricultural Sciences</dc:subject><dc:subject>Earth and Environmental Sciences</dc:subject><dc:subject>Upland rice</dc:subject><dc:subject>Micronutrients</dc:subject><dc:subject>Crop yield</dc:subject><dc:subject>Zinc</dc:subject><dc:subject>Boron</dc:subject><dc:subject>Latin America and the Caribbean</dc:subject><dc:subject>Multifunctional Landscapes</dc:subject><dc:language>Spanish, Castilian</dc:language><dc:date>2019-02</dc:date><dc:contributor>Garcia, Carolina</dc:contributor><dc:type>Experimental Data</dc:type><dc:type>Environmental Data</dc:type></oai_dc:dc></metadata></record></GetRecord>
```

Specifically, the three bytes that were representing the apostrophe, `<E2><80><99>` were turned into 4: `<EF><BF><BD><99>`. Of which the first 3 represent the UTF-8 character "�" and the last one - `<99>` - not a valid UTF8 character at all, hence the record above is invalid and cannot be parsed. 

The explanation is, as you have guessed, that the 1024 bytes offset splits the stream after the `<80>` byte. When in the next line it is converted to `new String(buffer, StandardCharsets.UTF_8);`, the 2 bytes are not recognized as a valid entity and replaced with the "�"; when the rest of the stream is written in `xmlInputStream.transferTo(writer.getOutputStream());`, the `<99>` byte is written as is, breaking everything. 

I can sit down and put together a quick fix that would involve checking if the string produced by `new String(buffer, StandardCharsets.UTF_8);` ends with a valid character, and if not, read additional bytes, one at a time, until it does. You'll never have to make more than 3 additional reads, with UTF-8. Knowing the first, incomplete bytes may be enough to unambiguously predict how many additional bytes need to be read - but I would not even bother, for the purposes of a quick-and-dumb fix. There may be prettier ways of solving this problem - which should really be fairly common. I have actually dealt with something like this in some other context a while ago (so, again, kicking myself now). I will check stackoverflow, there may even be standard methods for this.

### PR DESCRIPTION
**Pull request by poikilotherm**
Closes #188

### CODE REVIEW

**Comment by poikilotherm** [comment]
@landreev @pdurbin please take a look. Thx!

File: xoai-common/src/main/java/io/gdcc/xoai/xml/CopyElement.java [hunk 1]
```diff
@@ -82,19 +83,61 @@ protected void writeXml(XmlWriter writer) throws IOException {
...
+    public static int maxBytesWithCompleteUTF8Chars(final byte[] buffer) {
+        final int n = buffer.length;
+
+        if (Byte.toUnsignedInt(buffer[n - 1])
+                > 127) { // 0b0xxxxxxx are all 1-byte chars, so only seek for 0b1xxxxxxx
+            for (int i = n - 1;
+                    i > n - 5;
+                    i--) { // go max four bytes back (max UTF-8 mbchar length)
+                if (Byte.toUnsignedInt(buffer[i])
+                        > 191) { // 0b110xxxxx / 0b1110xxxx / 0b11110xxx are the UTF-8 multibyte
```
Comment (landreev) [inline xoai-common/src/main/java/io/gdcc/xoai/xml/CopyElement.java:131]: Just out of curiosity, was there anything objectively wrong with testing by converting the buffer to string, then checking if `firstChars.charAt(firstChars.length()-1) == '\uFFFD'`? - were there any cases of incomplete utf8 sequences that it wasn't going to cover?

**Review by landreev — APPROVED** [review]
I like the solution. 
And it's great to have tests for this! 
Thank you.

**Comment by pdurbin** [comment]
At sprint planning today I pulled this issue...

- https://github.com/IQSS/dataverse/issues/9910

... into the current sprint because it looks like we're close! Thanks @poikilotherm and @landreev!

File: xoai-common/src/main/java/io/gdcc/xoai/xml/CopyElement.java (hunk 1 above)
Comment (poikilotherm) [reply xoai-common/src/main/java/io/gdcc/xoai/xml/CopyElement.java:131]: There definitely is some bikeshedding involved here. 

I didn't do a real performance test, but I had the nagging feeling that converting to string multiple times instead of looking at the encoded char might be slower.

Other than that, I liked following the UTF-8 encoding schema better, not relying on codepoint vs char etc.
